"""
Custom Nuclei Templates

Stores Nuclei YAML templates that were either:
  - Written manually by an analyst
  - Generated by the AI Oracle agent for a specific CVE or vulnerability pattern

Templates are scoped to an organization and have a status lifecycle:
  draft    → generated/uploaded, not yet used in scans
  active   → included in Nuclei scan runs
  disabled → excluded from scans (soft delete)
"""

from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from app.db.database import Base


class CustomNucleiTemplate(Base):
    __tablename__ = "custom_nuclei_templates"

    id = Column(Integer, primary_key=True, index=True)

    # Org scope
    organization_id = Column(
        Integer, ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    organization = relationship("Organization")

    # Template identity (mirrors the `id` field inside the YAML)
    template_id = Column(String(128), nullable=False, index=True)
    # Scoped unique: same template_id can exist across orgs but not within one.
    name = Column(String(256), nullable=False)
    description = Column(Text, nullable=True)

    # The actual Nuclei YAML content
    template_yaml = Column(Text, nullable=False)

    # Classification (extracted from YAML or set by the generator)
    cve_ids = Column(JSON, default=list)       # ["CVE-2024-12345"]
    severity = Column(String(20), nullable=True)  # critical | high | medium | low | info
    tags = Column(JSON, default=list)          # ["rce", "apache", "log4j"]
    template_type = Column(String(20), nullable=True)  # http | network | tcp | dns | file

    # Source tracking
    source = Column(String(20), default="manual")  # manual | ai_generated
    ai_model = Column(String(64), nullable=True)   # which model was used
    ai_generation_context = Column(Text, nullable=True)  # CVE description / prompt context stored for reproducibility
    content_digest = Column(String(64), nullable=True)  # SHA-256 of YAML; safe provenance/version identifier

    # Lifecycle status
    status = Column(String(20), default="draft", nullable=False)
    # draft    → not yet used in scans (pending analyst review)
    # active   → included in Nuclei scan runs
    # disabled → soft-disabled, excluded from scans

    # Analyst validation flag (set manually after review)
    validated = Column(Boolean, default=False, nullable=False)
    validated_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    validated_at = Column(DateTime, nullable=True)

    # Durable lifecycle timestamps used by the CVE intelligence timeline.
    released_at = Column(DateTime, nullable=True, index=True)
    enabled_at = Column(DateTime, nullable=True, index=True)

    # Usage statistics (updated when Nuclei reports a match)
    last_run_at = Column(DateTime, nullable=True)
    times_matched = Column(Integer, default=0, nullable=False)
    last_match_at = Column(DateTime, nullable=True)

    # Authorship
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self) -> str:
        return f"<CustomNucleiTemplate {self.template_id} org={self.organization_id} status={self.status}>"
